[FIX] materiales_productreport: new way to calculate the "Valor del inventario"
rodrigozaz/zazsupercentro pull request #244
Opened 2022-10-27 21:08 UTC by eacm-odoo

-new way to calculate the "valor del inventario" for the product kardex report:
		total_value=cost*saldo

TASK ID: 3010207

2022-10-27 21:40 UTC, kak-odoo requested changes
Don't use an auto-formater, it makes commits longer and adds random noise to the commit that isn't captured by the task or the commit message.

2022-10-27 21:40 UTC, kak-odoo commented on materiales_productreport/views/product_report_template.xml
> +                        </strong>
There's no reason for this to be on separate lines, it will easily fit on one line

2022-10-27 21:40 UTC, kak-odoo commented on materiales_productreport/views/product_report_template.xml
> +                        </strong>
There's no reason for this to be on separate lines, it will easily fit on one line

2022-10-27 21:40 UTC, kak-odoo commented on materiales_productreport/views/product_report_template.xml
> +                            </strong>
There's no reason for this to be on separate lines, it will easily fit on one line

2022-10-27 21:40 UTC, kak-odoo commented on materiales_productreport/views/product_report_template.xml
> +                            <t t-set="total" t-value="product.qty_available" />
Don't put a space at the end of a self-closing tag

2022-10-27 21:40 UTC, kak-odoo commented on materiales_productreport/views/product_report_template.xml
> +                                        <span t-esc="stock.date" t-options='{"widget": "date"}' />
Don't put a space at the end of a self-closing tag

2022-10-27 21:40 UTC, kak-odoo commented on materiales_productreport/views/product_report_template.xml
> +                                            <span t-esc="stock.picking_id.name" />
Don't put a space at the end of a self-closing tag

2022-10-27 21:40 UTC, kak-odoo commented on materiales_productreport/views/product_report_template.xml
> +                                <t t-set="colspan" t-value="7" />
Don't put a space at the end of a self-closing tag

2022-10-27 21:40 UTC, kak-odoo commented on materiales_productreport/views/product_report_template.xml
> +                                </th>
All of these fit on one line each, there's no reason for it to be split

2022-10-27 21:40 UTC, kak-odoo commented on materiales_productreport/views/product_report_template.xml
> +                                        <span t-esc="int(stock.quantity_done)" />
Don't put a space at the end of a self-closing tag

2022-10-27 21:40 UTC, kak-odoo commented on materiales_productreport/views/product_report_template.xml
> +                                            <span t-esc="unit_cost" t-options='{"precision": 2, "widget": "float"}' />
Why are you assigning this to a variable, it's only used once.

Don't put a space at the end of a self-closing tag

2022-10-27 21:40 UTC, kak-odoo commented on materiales_productreport/views/product_report_template.xml
> +                                            <t t-esc="int(total)" />
Don't put a space at the end of a self-closing tag

2022-10-27 21:40 UTC, kak-odoo commented on materiales_productreport/views/product_report_template.xml
> +                                            <t t-esc="int(total)" />
Don't put a space at the end of a self-closing tag

2022-10-27 21:49 UTC, eacm-odoo commented on materiales_productreport/views/product_report_template.xml
> +                                            <span t-esc="unit_cost" t-options='{"precision": 2, "widget": "float"}' />
Hey thanks for the comments! I won't use auto-formater anymore, 
the unit_cost i used to calculate the "valor del inventario"
<td class="text-center">
                                        <span t-esc="unit_cost * total" t-options='{"precision": 2, "widget": "float"}'/>
                                    </td>
line 81

2022-11-03 21:17 UTC, kak-odoo approved these changes

2022-11-03 21:24 UTC, merged